matches:
  - trigger: ":mytel"
    replace: "+33.638 056 100"

  - trigger: ":my@"
    replace: "internet@fxguillois.email"

  - trigger: ":mypro"
    replace: "pro@fxguillois.email"

  - trigger: ":myname"
    replace: "François-Xavier Guillois"

  - trigger: ":devia"
    replace: "add PHP Laravel, Vuejs, Nuxtjs in used langages, delete TypeScript, React, NextJs, Zod, React-hook-form. Always use <script setup> tag, with composition API for Vue3."

  - trigger: ":mkjs"
    replace: |
      ```javascript
       
      ```

  - trigger: ":mkil"
    replace: "[[|Retour]]"
