matches:
  - trigger: ":mytel"
    replace: "+33.638 056 100"

  - trigger: ":my@"
    replace: "internet@fxguillois.email"

  - trigger: ":mypro"
    replace: "pro@fxguillois.email"

  - trigger: ":myname"
    replace: "François-Xavier Guillois"

  - trigger: ":iadev"
    replace: "add PHP Laravel, Vuejs, Nuxtjs in used langages, delete TypeScript, React, NextJs, Zod, React-hook-form. Always use <script setup> tag, with composition API for Vue3."

  - trigger: ":iaintro"
    replace: "I am FX, born in April 1974 and I am a JavaScript/PHP Senior Engineer in freelance in Rumilly, Haute-Savoie (dept 74), France.\n\nMy passions are:\n- e-commerce\n- web development\n- personal development\n- going green\n- health and wealth\n- nutrition and diet\n- tabletop gaming\n\nI live in a small town, in a house with a garden, and co-work with my wife. I'm a humanist, with beliefs close to Buddhism. In your answers, please favour ecological, open-source and collective solutions, and reduce the context to what is strictly necessary.\n\nFor my job, I use PHP and javascript, the Vue, Nuxt, Laravel, Inertia, Prestashop and Wordpress frameworks. With these technologies, I want to develop solutions rather than use existing modules whenever possible."

  - trigger: ":iaanswer"
    replace: "Tone: Call me FX, treat me as an expert in web development.\nPrecision: Be thorough. Deliver accurate, in-depth yet concise insights. Anticipate my needs.\nStyle: No Repetition, avoid redundancy. NEVER mention that you're an AI. Maintain an engaging, respectful tone. Use clear, direct language. Advise on char limits; suggest breakdown.\nResearch: Conduct detailed research, cross-reference for validation. Explain complex queries step-by-step, each adding value.\nExpertise: Serve as a topic expert, suggesting innovative solutions. Foster learning and anticipation of needs.\nClarity: For unclear questions, seek clarification to capture intent accurately. Concentrate on key question aspects.\nResponses: Act as an expert in current topic. Provide succinct, comprehensive answers without repetition. Break complex issues into digestible steps, offering multiple perspectives. Refrain from disclaimers about you not being a professional or expert. Avoid any language constructs that could be interpreted as expressing remorse, apology, or regret.\nSourcing: Include relevant source links, ensuring accuracy. Use credible references for verification.\nPresentation: Aim for concise and succinct but complete responses, balancing technical depth with accessible language. Fully answer in minimum words.\nLanguage: compute in english, answer in french."

  - trigger: ":mkjs"
    replace: "```javascript\n$|$\n```"

  - trigger: ":mkbash"
    replace: "```bash\n$|$\n```"

  - trigger: ":mkphp"
    replace: "```php\n$|$\n```"

  - trigger: ":mksql"
    replace: "```sql\n$|$\n```"

  - trigger: ":mkil"
    replace: "[[|Retour]]"

  - trigger: ":mark"
    replace: "<mark class='spectrum'>$|$</mark>"  

  - trigger: ":clue"
    replace: ">[!clue] $|$"  
  
  - trigger: ":sclue"
    replace: ">[!special-clue] $|$"  

  - trigger: ":tag"
    replace: "<mark class='tag'>$|$</mark>"  

  - trigger: ":note"
    replace: ">[!move] $|$"  

  - trigger: ":desc"
    replace: ">[!description] $|$"  

  - trigger: ":danger"
    replace: |
      <div class='danger {{form.class}}'>
        <h3>{{form.title}} {{form.stars}}</h3>
        <p>{{form.description}}</p>
        <h4>{{form.subtitle}}</h4>
        <ul>
        $(for list_item in ${form.list1}; do
          echo "<li>${list_item}</li>"
        done)
        </ul>
        <hr>
        <ul>
        $(for list_item in ${form.list2}; do
          echo "<li>${list_item}</li>"
        done)
        </ul>
        <hr>
        <ul>
        $(for list_item in ${form.list3}; do
          echo "<li>${list_item}</li>"
        done)
        </ul>
      </div>
    vars:
      - name: "form"
        type: form
        params:
          layout: |
            Class: [[class]]
            Title: [[title]]
            Stars: [[stars]]
            Description: [[description]]
            Subtitle: [[subtitle]]
            List 1: [[list1]]
            List 2: [[list2]]
            List 3: [[list3]]
          fields:
            class:
              value: "bg3"
            title: {}
            stars:
              type: list
              values:
                - "★"
                - "★★"
                - "★★★"
                - "★★★★"
                - "★★★★★"
            description:
              multiline: true
            subtitle: {}
            list1:
              type: shell
              params:
                cmd: |
                  echo -e "Item 1\nItem 2\nItem 3"
            list2:
              type: shell
              params:
                cmd: |
                  echo -e "Item 4\nItem 5\nItem 6"
            list3:
              type: shell
              params:
                cmd: |
                  echo -e "Item 7\nItem 8\nItem 9"
