matches:
  - trigger: ":mytel"
    replace: "+33.638 056 100"

  - trigger: ":my@"
    replace: "internet@fxguillois.email"

  - trigger: ":mypro"
    replace: "pro@fxguillois.email"

  - trigger: ":myname"
    replace: "François-Xavier Guillois"

  - trigger: ":devia"
    replace: "add PHP Laravel, Vuejs, Nuxtjs in used langages, delete React, NextJs, Zod, React-hook-form"
