matches:
  - trigger: ":mark"
    replace: "<mark class='spectrum'>$|$</mark>"  

  - trigger: ":clue"
    replace: ">[!clue] $|$"  
  
  - trigger: ":sclue"
    replace: ">[!special-clue] $|$"  

  - trigger: ":tag"
    replace: "<mark class='tag'>$|$</mark>"  

  - trigger: ":status"
    replace: "<mark class='status'>$|$</mark>"  

  - trigger: ":note"
    replace: ">[!move] $|$"  

  - trigger: ":desc"
    replace: ">[!description] $|$"  

  - trigger: ":danger"
    replace: |
      <div class='danger {{form.class}}'>
        <h3>{{form.title}} {{form.stars}}</h3>
        <p>{{form.description}}</p>
        <h4>{{form.subtitle}}</h4>
        <ul>
        $(for list_item in ${form.list1}; do
          echo "<li>${list_item}</li>"
        done)
        </ul>
        <hr>
        <ul>
        $(for list_item in ${form.list2}; do
          echo "<li>${list_item}</li>"
        done)
        </ul>
        <hr>
        <ul>
        $(for list_item in ${form.list3}; do
          echo "<li>${list_item}</li>"
        done)
        </ul>
      </div>
    vars:
      - name: "form"
        type: form
        params:
          layout: |
            Class: [[class]]
            Title: [[title]]
            Stars: [[stars]]
            Description: [[description]]
            Subtitle: [[subtitle]]
            List 1: [[list1]]
            List 2: [[list2]]
            List 3: [[list3]]
          fields:
            class:
              value: "bg3"
            title: {}
            stars:
              type: list
              values:
                - "★"
                - "★★"
                - "★★★"
                - "★★★★"
                - "★★★★★"
            description:
              multiline: true
            subtitle: {}
            list1:
              type: shell
              params:
                cmd: |
                  echo -e "Item 1\nItem 2\nItem 3"
            list2:
              type: shell
              params:
                cmd: |
                  echo -e "Item 4\nItem 5\nItem 6"
            list3:
              type: shell
              params:
                cmd: |
                  echo -e "Item 7\nItem 8\nItem 9"
