matches:
  - trigger: ":mark"
    replace: "<mark class='spectrum'>$|$</mark>"  

  - trigger: ":clue"
    replace: ">[!clue] $|$"  
  
  - trigger: ":sclue"
    replace: ">[!special-clue] $|$"  

  - trigger: ":tag"
    replace: "<mark class='tag'>$|$</mark>"  

  - trigger: ":status"
    replace: "<mark class='status'>$|$</mark>"  

  - trigger: ":note"
    replace: ">[!move] $|$"  

  - trigger: ":desc"
    replace: ">[!description] $|$"  

  - trigger: ":danger"
    replace: |
      <div class='danger {{form.class}}'>
        <h3>{{form.title}} {{form.stars}}</h3>
        <p>{{form.description}}</p>
        <h4>{{form.subtitle}}</h4>
        <ul>
          {{ form.list1 | replace('\n', '\n<li>') | safe }}
        </ul>
        <hr>
        <ul>
          {{form.list2}}
        </ul>
        <hr>
        <ul>
          {{form.list3}}
        </ul>
      </div>
    vars:
      - name: "form"
        type: form
        params:
          layout: |
            Class: [[class]]
            Title: [[title]]
            Stars: [[stars]]
            Description: [[description]]
            Subtitle: [[subtitle]]
            List 1: 
              multiline: true
            List 2: [[list2]]
            List 3: [[list3]]
          fields:
            class:
              value: "bg3"
            title: {}
            stars:
              type: list
              values:
                - " "
                - "★"
                - "★★"
                - "★★★"
                - "★★★★"
                - "★★★★★"
            description:
              multiline: true
            subtitle: {}
            list1:
              type: text
              multiline: true
            list2:
              multiline: true
            list3:
              multiline: true
