matches:
  - trigger: ":mytel1"
    replace: "+33.638 056 100"

  - trigger: ":mytel2"
    replace: "+33.684 510 375"

  - trigger: ":my@"
    replace: "internet@fxguillois.email"

  - trigger: ":mypro"
    replace: "pro@fxguillois.email"

  - trigger: ":myname"
    replace: "François-Xavier Guillois"

  - trigger: ":sign"
    replace: |-
      ---
      François-Xavier Guillois
      06 84 51 03 75
      Messagerie instantanée sur Signal (https://signal.me/#eu/T-BmyvkxPeRs3bSj852ie8yG7fXhqUyNK0FOTYwlLulDD7o8Z5VL8bfAzFEqRXlM)

  - trigger: ":sigcab"
    replace: |-
      ---
      François-Xavier Guillois - Cabinet partagé / Racines (Chambéry) / Lumi (Vallières)
      06 38 056 100 - location@cabinet-partage.fr
      Support en temps réel sur Signal (https://signal.me/#eu/T-BmyvkxPeRs3bSj852ie8yG7fXhqUyNK0FOTYwlLulDD7o8Z5VL8bfAzFEqRXlM)
  - trigger: ":sigperso"
    replace: |-
      ---
      François-Xavier "tnn/fx" Guillois
      https://fxguillois.email/

  - trigger: ":sigsl"
    replace: |-
      ---
      François-Xavier Guillois - Développeur PHP/JS chez Smartlockers
      https://www.smartlockers.io
      +33.638 056 100

  - trigger: ":sigpro"
    replace: |-
      ---
      François-Xavier Guillois - Développeur PHP/JS Laravel/VueJS/Prestashop/Wordpress
      https://www.scriptami.com - Messagerie instantanée sur Signal (https://signal.me/#eu/T-BmyvkxPeRs3bSj852ie8yG7fXhqUyNK0FOTYwlLulDD7o8Z5VL8bfAzFEqRXlM)
      +33.638 056 100

  - trigger: ":iadev"
    replace: "add PHP Laravel, Vuejs, Nuxtjs in used langages, delete TypeScript, React, NextJs, Zod, React-hook-form. Always use <script setup> tag, with composition API for Vue3."

  
  - trigger: ":jsDocScript"
    replace: "tree -L 3 -I 'node_modules|documentation|.vscode' > documentation/arborescence.txt && jsdoc -r -c jsdoc.json src -d ./documentation/jsdocs && npx jsdoc-to-markdown --json src/**/*.js > documentation/rag.json"

  - trigger: ":oneta"
    replace: "{ \"msg\":{ \"expire\":\"2024-05-27 10:29:18\", \"from\":\"peripheral\", \"payload\":{ \"data\":\"9014BB527B8B04\", \"module\":\"rd4500r\" }, \"to\":\"*\", \"type\":\"EVT\" }, \"sign\":\"la signature\" }"



